### ISSUE TITLE
dimension labels ('dims' field in spec) are not used by pynwb 

### ISSUE THREAD

**Issue by tjd2002** [NeurodataWithoutBorders/nwb-schema#247]
The spec allows for the labeling of dimensions of datasets in the spec, but these are not used by pynwb.

 For example, the spec for a behavior.Position group includes the dimension labels 'num_times' and 'num_features' for 2-D data:
https://github.com/NeurodataWithoutBorders/pynwb/blob/f21aa5d844a737fbb7773773b477d3868495d82d/src/pynwb/data/nwb.behavior.yaml#L33-L36

But these do not appear to be written into the resulting nwb file by pynwb. 

One option would be for pynwb to write these to the 'dims' fields of the HDF5 dataset, however this is not currently done.

```python
import pynwb
import numpy as np
from datetime import datetime
from dateutil import tz

nwb_filename = './test.nwb'

nwbf=nwbf = pynwb.NWBFile(session_description='example session',
                         identifier='example1',
                         session_start_time=datetime.now(tz.tzlocal()))
pos = pynwb.behavior.Position(spatial_series=[], 
                              name='Position')
pos.create_spatial_series(name='Position Data', 
                              timestamps = np.arange(5),
                              data=np.ones((5,2)),
                              reference_frame='top-left corner of video frame')
behav_mod = nwbf.create_processing_module(name='Behavior', 
                                          description='Behavioral variables')
behav_mod.add_data_interface(pos)

with pynwb.NWBHDF5IO(nwb_filename, mode='w') as iow:
    iow.write(nwbf)

io = pynwb.NWBHDF5IO(nwb_filename, mode='r')
nwbf_read = io.read()

print('*** SpatialSeries before writing (data is np.array), no dim labels')
print(nwbf_read.modules['Behavior']['Position']['Position Data'])
print()
print('*** SpatialSeries as read from nwb file (data is HDF5 dataset), no dim labels')
print(nwbf_read.modules['Behavior']['Position']['Position Data'])
print()
print('*** HDF5 "dims" fields are empty')
print(nwbf_read.modules['Behavior']['Position']['Position Data'].data.dims)
for dim in nwbf_read.modules['Behavior']['Position']['Position Data'].data.dims: 
    print(dim)
io.close()
```
results:
```
*** SpatialSeries before writing (data is np.array), no dim labels

Position Data <class 'pynwb.behavior.SpatialSeries'>
Fields:
  comments: no comments
  conversion: 1.0
  data: <HDF5 dataset "data": shape (5, 2), type "<f8">
  description: no description
  interval: 1
  num_samples: 5
  reference_frame: top-left corner of video frame
  resolution: 0.0
  timestamps: <HDF5 dataset "timestamps": shape (5,), type "<f8">
  timestamps_unit: Seconds
  unit: meters


*** SpatialSeries as read from nwb file (data is HDF5 dataset), no dim labels

Position Data <class 'pynwb.behavior.SpatialSeries'>
Fields:
  comments: no comments
  conversion: 1.0
  data: <HDF5 dataset "data": shape (5, 2), type "<f8">
  description: no description
  interval: 1
  num_samples: 5
  reference_frame: top-left corner of video frame
  resolution: 0.0
  timestamps: <HDF5 dataset "timestamps": shape (5,), type "<f8">
  timestamps_unit: Seconds
  unit: meters


*** HDF5 "dims" fields are empty
<Dimensions of HDF5 object at 4603206384>
<"" dimension 0 of HDF5 dataset at 4603206384>
<"" dimension 1 of HDF5 dataset at 4603206384>
```
