### ISSUE TITLE
Remove 'help' attribute broadly

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-schema#270]
What is the difference between the 'doc' field and the 'help' field? They appear to mean the same thing.

e.g. 
```yaml
groups:
- neurodata_type_def: Transcription
  neurodata_type_inc: NWBDataInterface
  name: transcription
  doc: holds tiers for different levels of transcription (e.g. sentence, word, phoneme)
  attributes:
  - name: help
    dtype: text
    doc: doc
    value: holds tiers for different levels of transcription
```
and
```yaml
groups:
- neurodata_type_def: NWBFile
  neurodata_type_inc: NWBContainer
  name: root
  doc: Top level of NWB file.
  attributes:
  - name: help
    dtype: text
    doc: Value is 'an NWB:N file for storing cellular-based neurophysiology data'
    value: an NWB:N file for storing cellular-based neurophysiology data
```

The `help` attribute also has a `doc` field. What is that intended for?
