### ISSUE TITLE
Remove Index type?

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-schema#276]
The `Index` type is used only by `VectorIndex`. It seems to be an unnecessary level in the class hierarchy. Perhaps a `MatrixIndex` type was planned? Can we remove this in favor in order to simplify the schema? In PyNWB, Index is used only as the superclass for VectorIndex. 

```yaml
- neurodata_type_def: Index
  neurodata_type_inc: NWBData
  doc: Pointers that index data values
  attributes:
  - name: help
    dtype: text
    doc: a help string
    value: indexes into a list of values for a list of elements
  - name: target
    dtype:
      target_type: NWBData
      reftype: object
    doc: the target dataset that this index applies to
```
