### ISSUE TITLE
Clean up TimeIntervals type

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-schema#282]
In `nwb.epoch.yaml`, the `description` attribute for the datasets `start_time`, `stop_time`, and `tags` are fixed text strings that seem to exist for the sole purpose of writing those strings to the file. 
1) I think these attributes should have the `help` key instead.
2) Given that we will be caching the spec, I think these attributes can be removed entirely. See https://github.com/NeurodataWithoutBorders/nwb-schema/issues/270

```yaml
groups:
- neurodata_type_def: TimeIntervals
  neurodata_type_inc: DynamicTable
  doc: A container for aggregating epoch data and the TimeSeries that each epoch applies
    to
  attributes:
  - name: help
    dtype: text
    value: A general epoch object
    doc: Value is 'A general epoch object'
  datasets:
  - name: start_time
    neurodata_type_inc: VectorData
    dtype: float
    doc: Start time of epoch, in seconds
    attributes:
    - name: description
      dtype: text
      value: start time of the epoch, in seconds
      doc: value is 'start time of the epoch, in seconds'
  - name: stop_time
    neurodata_type_inc: VectorData
    dtype: float
    doc: Stop time of epoch, in seconds
    attributes:
    - name: description
      dtype: text
      value: stop time of the epoch, in seconds
      doc: value is 'stop time of the epoch, in seconds'
  - name: tags
    neurodata_type_inc: VectorData
    dtype: text
    doc: User-defined tags that identify events. Tags are to help identify or categorize
      events.
    quantity: '?'
    attributes:
    - name: description
      dtype: text
      value: user-defined tags
      doc: value is 'user-defined tags'
  - name: tags_index
    neurodata_type_inc: VectorIndex
    doc: Index for tags
    quantity: '?'
  - name: timeseries
    neurodata_type_inc: VectorData
    dtype:
    - name: idx_start
      dtype: int32
      doc: 'Start index into the TimeSeries data[] field. COMMENT: This can be used
        to calculate location in TimeSeries timestamp[] field'
    - name: count
      dtype: int32
      doc: Number of data samples available in this time series, during this epoch.
    - name: timeseries
      dtype:
        target_type: TimeSeries
        reftype: object
      doc: the TimeSeries that this index applies to
    doc: An index into a TimeSeries object
    quantity: '?'
    attributes:
    - name: help
      dtype: text
      value: Data on how an epoch applies to a time series
      doc: Value is 'Data on how an epoch applies to a time series'
  - name: timeseries_index
    neurodata_type_inc: VectorIndex
    doc: Index for timeseries
    quantity: '?'
```
