### ISSUE TITLE
new neurodata_type: TTL pulse

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-schema#306]
It would be nice to have an intuitive and machine-readable neurodata_type for TTL pulses. Something like

```yaml
neurodata_type_def: TTL
neurodata_type_ind: TimeSeries
datasets:
  - name: data
    shape:
      - None
    dims:
      - pulses
    dtype: int
 - name: keys
   shape:
     - None
   dims:
     - unique_labels
   dtype: int
 - name: labels
   shape:
     - None
   dims:
     - unique_labels
   dtype: text
```
