### ISSUE TITLE
Refine Subject Weight dataset

### ISSUE THREAD

**Issue by oruebel** [NeurodataWithoutBorders/nwb-schema#476]
```Subject.weight``` is currently a free-form text dataset. Based on the description ```Weight at time of experiment, at time of surgery and at other important``` it is also seems to be intended to store not just a single measurement but a series of weight measurements at different times. 

https://github.com/NeurodataWithoutBorders/nwb-schema/blob/2fc379e09f66ddbde6c06947fa1b94dae1189990/core/nwb.file.yaml#L430-L434

**Problems:**
1. missing unit for weight, 
2. no prescribed formatting for storing multiple measurements, making  the field hard to use programmatically 

**Suggested change:**
1. Add attribute ``unit`` with default (or fixed) value of ``kilograms``
2. Change ``dtype`` of the dataset to ``float``
3. Change docstring to ``weight of the subject at the time of the session``
4. Add a new compound dataset ``weights`` to store multiple weight measurements. 

```
 - name: weight    
    dtype: 
    - name: weigth
       dtype: float
       doc: weight in kilograms
    -  name: datetime
       dtype: isodatetime
       doc: time of measurement
    - name: description
       dtype: text
       doc: Description of the time of measurement during the experiment, e.g., before surgery. 
    doc: Weight at time of experiment, at time of surgery and at other important times.
    quantity: '?' 
``` 

Alternatively, we could also change ``weight`` itself to become a compound dataset instead of adding a new field. Adding a separate field may be easier for backward compatibility and having a reference weight seemed also useful to have in addition to a collection of weight measurements.
