### ISSUE TITLE
Docs: Add description of support for compound types

### ISSUE THREAD

**Issue by oruebel** [NeurodataWithoutBorders/nwb-schema#51]
* **Specification Language Docs:** Update docs to describe how compound types are specified
* **Specification Language Release Notes:** Add note about the addition of compound types
* **Storage docs:** Add description on how compound types are mapped to HDF5

**Comment by oruebel** [comment]
Just for reference, an example of how a compound data type will be expressed in the specification language is here: 

https://github.com/NeurodataWithoutBorders/pynwb/blob/enh/tables/src/pynwb/data/nwb.ecephys.yaml

```
datasets:
- doc: 'a table for storing queryable information about electrodes in a single table'
  dtype:
  - name: id
    dtype: int
    doc: a user-specified unique identifier
  - name: x
    dtype: float
    doc: the x coordinate of the channels location
  - name: y
    dtype: float
    doc: the y coordinate of the channels location
  - name: z
    dtype: float
    doc: the z coordinate of the channels location
  - name: imp
    dtype: float
    doc: the impedance of the channel
  - name: location
    dtype: ascii
    doc: the location of channel within the subject e.g. brain region
  - name: filtering
    dtype: ascii
    doc: description of hardware filtering
  - name: description
    dtype: utf8
    doc: a brief description of what this electrode is
  - name: group
    dtype: ascii
    doc: the name of the ElectrodeGroup this electrode is a part of
  - name: group_ref
    dtype:
        target_type: ElectrodeGroup
        reftype: object
    doc: a reference to the ElectrodeGroup this electrode is a part of
  attributes:
    - doc: Value is 'a table for storing data about extracellular electrodes'
      dtype: text
      name: help
      value: a table for storing data about extracellular electrodes
  neurodata_type_inc: NWBData
neurodata_type_def: ElectrodeTable
```
