### ISSUE TITLE
Suggestion: Use "default_value: null" for unused  fields in IndexSeries

### ISSUE THREAD

**Issue by ehennestad** [NeurodataWithoutBorders/nwb-schema#641]
In `IndexSeries`, the data attributes are not used, but the specification only states this in the doc. 

https://github.com/NeurodataWithoutBorders/nwb-schema/blob/764aa372536db61339ec4ae578e0b375b4b54829/core/nwb.image.yaml#L202-L218

An alternative way to ensure the schema more explicitly enforces this is to set `default_value: null` for these attributes, similar to how `value: N/A` is already used for the `unit` attribute:

```yaml
    attributes:
    - name: conversion
      doc: This field is unused by IndexSeries.
      default_value: null
    - name: resolution
      doc: This field is unused by IndexSeries.
      default_value: null
    - name: offset
      default_value: null
      doc: This field is unused by IndexSeries.
    - name: unit
      value: N/A
      doc: This field is unused by IndexSeries and has the value N/A.
```

Edit: Based on discussion, changed original suggestion of specifying `value` to specifying `default_value` instead
