### ISSUE TITLE
Missing 'quantity' on TimeSeries nwb.base.yaml

### ISSUE THREAD

**Issue by nicain** [NeurodataWithoutBorders/nwb-schema#75]
Currently TimeSeries has not 'quantity'

https://github.com/NeurodataWithoutBorders/nwb-schema/blob/902c2f036f72cce8ce3531d5e51bbcf8064602af/core/nwb.base.yaml#L114

@ajtritt and @nicain Identified this and corrected it in pynwb (currently in a feature branch, but will be rolled into dev/master before SfN2017 milestone), but that change will need to be corrected here too.  Suggested change is :

```
    dtype: float64!
    name: timestamps
    shape:
    - null
```

Becomes:

```
    dtype: float64!
    name: timestamps
    quantity: '?'
    shape:
    - null
```
